services:
  main:
    volumes:
      - ${HOST_VERIFIER_LOGS_PATH}:${ENV_VERIFIER_LOGS_PATH}
      - ${HOST_AGENT_LOGS_PATH}:${ENV_AGENT_LOGS_PATH}
      - ${HOST_ARTIFACTS_PATH}:${ENV_ARTIFACTS_PATH}
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
